### ISSUE TITLE
Test production scenarios locally

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/cli#141]
I'd like to propose we add the following command:

```bash
d2 cluster installApp <cluster_name> <src_folder> <app_name>
```

For example, suppose I've just built the data-administration-app and I want to see how it will behave once deployed. And given the following:
- My cluster is called `master`
- Build artefacts are at `~/apps/data-administration-app/build`

I would run:
```bash
d2 cluster installApp master ~/apps/data-administration-app/build data-administration-app
```

And the following command would be executed:
```bash
docker cp ~/apps/data-administration-app/build d2-cluster-master_core_1:/usr/local/tomcat/webapps/ROOT/dhis-web-data-administration
```

Something like the above would be good I think

**Comment by amcgee** [comment]
@HendrikThePendric yeah, I agree with this completely!  I'd suggest maybe a few small changes, but installing apps to clusters for testing is definitely something we want to support!

`d2 cluster apps` should probably be a namespace, with various commands like `list`, `install`, `uninstall`, etc.

`d2 cluster apps install` should usually use the API to install the app, rather than copying files manually.  I realize this makes it a bit more challenging to test apps we currently bundle, though, so maybe we have to copy files for now (I'd prefer to avoid explicitly supporting this since we want to move away from bundled apps anyway)

For platform apps we hope to add two commands, 
- `d2-app-scripts publish` which pushes the app to the DHIS2 app store (also to be used on Travis)
- `d2-app-scripts deploy` or maybe `d2-app-scripts install` which uses the API to install the app in a running instance.  This would cover the case of installing an app to a running cluster, but maybe it makes sense to have both options (especially since the latter could support non-platform apps)

**Comment by HendrikThePendric** [comment]
@amcgee glad you agree this would be useful. I'm completely on board with the approach you suggest.

**Comment by HendrikThePendric** [comment]
I believe this is still relevant, just not very urgent. I think we should keep this one open.
